from pathlib import Path


def load_rrg_report(report_path: str) -> str:
    """
    Load a radiology report generated by the RRG.

    Parameters
    ----------
    report_path : str
        Path to the RRG-generated report (.txt)

    Returns
    -------
    str
        Report text
    """
    path = Path(report_path)

    if not path.exists():
        raise FileNotFoundError(f"RRG report not found: {report_path}")

    return path.read_text(encoding="utf-8")
